listen = "[::]:53"
default_server = ["192.168.1.1"]

[[rules]]
type = "local"
domain_files = ["local.txt"]

[[rules]]
type = "block"
domain_files = ["blocklist.txt"]

[[rules]]
name = "gfw"
type = "forward"
domain_files = ["gfw.txt"]
upstreams = ["1.1.1.1"]
block_aaaa = true
nft_set = "inet fw4 fq"

[[rules]]
type = "forward"
domain_files = ["correct.txt"]
upstreams = ["1.1.1.1"]
