listen = "127.0.0.1:5354"
upstream = ["8.8.8.8", "114.114.114.114"]

[[rules]]
name = "gfw"
domain_files = ["domains/gfw.txt"]
upstreams = ["192.0.0.1"]
# upstreams = ["1.1.1.1", "192.0.0.1"]
block_aaaa = true
nft_set = "inet fw xip"
